plugins {
    id "com.android.application"
}

android {
    namespace "com.pluskey.remapper"
    compileSdk 35

    defaultConfig {
        applicationId "com.pluskey.remapper"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }
}

tasks.register("unitTestClasses") {
    dependsOn("compileDebugUnitTestJavaWithJavac")
}

tasks.register("androidTestClasses") {
    dependsOn("compileDebugAndroidTestJavaWithJavac")
}
